mezzanine_people/urls.py
from django.conf.urls import patterns, include, url

# People patterns.
urlpatterns = patterns("mezzanine_people.views",
    url("^category/(?P<category>.*)/$", "person_list", name="person_list_category"),
    url("^person/(?P<slug>[-\w]+)/$", "person_detail", name="person_detail"),
    url("^$", "person_list", name="person_list"),
)

mezzanine_people/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from mezzanine.conf import settings
from mezzanine.core.fields import RichTextField, FileField
from mezzanine.core.models import Displayable, RichText, Slugged
from mezzanine.utils.models import AdminThumbMixin


class Person(Displayable, RichText, AdminThumbMixin):
    """
    A person.
    """

    categories = models.ManyToManyField("PersonCategory",
                                        verbose_name=_("Categories"),
                                        blank=True, related_name="people")
    first_name = models.CharField(_("first name"), blank=True, max_length=100)
    last_name = models.CharField(_("last name"), blank=True, max_length=100)
    mugshot = FileField(verbose_name=_("Profile photo"),
                        upload_to="people", format="Image",
                        max_length=255, null=True, blank=True)
    mugshot_credit = models.CharField(_("Profile photo credit"), blank=True, max_length=200)
    email = models.EmailField(_("e-mail address"), blank=True)
    bio = RichTextField(_("biography"),
                          help_text=_("This field can contain HTML and should contain a few paragraphs describing the background of the person."),
                          default="", blank=True)
    job_title = models.CharField(_("job title"), max_length=60, blank=True, help_text=_("Example: First Grade Teacher"))
    order = models.PositiveSmallIntegerField(default=0)
    admin_thumb_field = "mugshot"
    search_fields = {"first_name", "last_name", "bio", "job_title",}

    class Meta:
        verbose_name = _("Person")
        verbose_name_plural = _("People")
        ordering = ("order", "last_name", "first_name",)

    @property
    def full_name(self):
        return u'%s %s' % (self.first_name, self.last_name)

    @models.permalink
    def get_absolute_url(self):
        return ("person_detail", (), {"slug": self.slug})

class PersonLink(models.Model):
    """
    A link to a person's interesting URLs, such as Twitter or Facebook
    """
    name = models.CharField(_("link name"), max_length=50, help_text=_("Friendly name of the link. E.g. Twitter"))
    url = models.URLField(_("URL"))
    person = models.ForeignKey(Person)

    class Meta:
        ordering = ('name',)

class PersonCategory(Slugged):
    """
    A category for grouping people.
    """

    class Meta:
        verbose_name = _("Person Category")
        verbose_name_plural = _("Person Categories")

    @models.permalink
    def get_absolute_url(self):
        return ("person_list_category", (), {"slug": self.slug})

mezzanine_people/views.py
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404
#from django import VERSION

from .models import Person, PersonCategory
from mezzanine.conf import settings
from mezzanine.generic.models import AssignedKeyword, Keyword
from mezzanine.utils.views import render, paginate


def person_list(request, category=None, template="mezzanine_people/person_list.html"):
    """
    Display a list of people that are filtered by category.
    Custom templates are checked for using the name
    ``people/person_list_XXX.html`` where ``XXX`` is the category's slug.
    """
    settings.use_editable()
    templates = []
    people = Person.objects.published()
    if category is not None:
        category = get_object_or_404(PersonCategory, slug=category)
        people = people.filter(categories=category)
        templates.append(u"mezzanine_people/person_list_%s.html" %
                          unicode(category.slug))

    # requires Django VERSION >= (1, 4):
    people = people.prefetch_related("categories")

    people = paginate(people, request.GET.get("page", 1),
                      settings.PEOPLE_PER_PAGE,
                      settings.MAX_PAGING_LINKS)
    context = {"people": people, "category": category}
    templates.append(template)
    return render(request, templates, context)


def person_detail(request, slug,
                  template="mezzanine_people/person_detail.html"):
    """
    Custom templates are checked for using the name
    ``mezzanine_people/person_detail_XXX.html`` where ``XXX`` is the
    person's slug.
    """
    people = Person.objects.published()
    person = get_object_or_404(people, slug=slug)
    context = {"person": person, "editable_obj": person}
    templates = [u"mezzanine_people/person_detail_%s.html" % unicode(slug), template]
    return render(request, templates, context)

mezzanine_people/templates/mezzanine_people/person_detail.html
{% extends "base.html" %}
{% load mezzanine_tags keyword_tags i18n %}

{% block meta_title %}{% if person %}{{ person.full_name }}{% else %}{% trans "Person" %}{% endif %}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for person as keywords %}
{% for keyword in keywords %}{% if not forloop.first %}, {% endif %}{{ keyword }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ person.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% if page %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% else %}
{% editable person.title %}{{ person.title }}{% endeditable %}
{% endif %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li class="active">{{ person.title }}</li>
{% endblock %}

{% block main %}

<h1>{{ person.full_name }}, {{ person.job_title }}</h1>

{% editable person.first_name person.last_name person.job_title person.bio %}
<div>
  <!-- image -->
  <img src="{{ MEDIA_URL }}{% thumbnail person.mugshot 300 0 %}" />
</div>
{% endeditable %}

<div>
  <p>Links:</p>
  <ul>
    {% for link in person.personlink_set.all %}
    <li><a href="{{ link.url }}">{{ link.name }}</a></li>
    {% endfor %}
  </ul>
</div>

<p>{{ person.bio|richtext_filters|safe }}</p>

{% endblock %}

mezzanine_people/templates/mezzanine_people/person_list.html
{% extends "base.html" %}
{% load mezzanine_tags keyword_tags i18n %}

{% block meta_title %}{% if page %}{{ page.richtextpage.meta_title }}{% else %}{% trans "People" %}{% endif %}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}{% if not forloop.first %}, {% endif %}{{ keyword }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% if page %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% else %}
{% trans "People" %}
{% endif %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
{% if category %}
<li>{% trans "Category:" %} {{ category }}<li>
{% endif %}
{% endblock %}

{% block main %}

{% if category %}
  <p>
  {% if category %}
    {{ category }}
  {% else %}
    {% trans "People" %}
  {% endif %}
  </p>
{% else %}
  {% if page %}
  {% editable page.richtextpage.content %}
  {{ page.richtextpage.content|safe }}
  {% endeditable %}
  {% endif %}
{% endif %}

{% for person in people %}
{% editable person.first_name person.last_name person.job_title person.bio %}
<div>
  <img src="{{ MEDIA_URL }}{% thumbnail person.mugshot 100 0 %}" />
  <h3><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></h3>
  <h4>{{ person.job_title }}</h4>
  <ul>
  {% for link in person.personlink_set.all %}
    <li><a href="{{ link.url }}">{{ link.name }}</a></li>
  {% endfor %}
  </ul>
  <p>{{ person.bio|richtext_filter|safe }}</p>
</div>
{% endeditable %}
{% endfor %}

{% pagination_for people %}

{% endblock %}